data:
  batch_size: 32
  data_dir: data/processed
  num_workers: 0
  shuffle: true
deployment:
  buildings_per_round: 10
labeling:
  electricity_price: 0.25
  feed_in_tariff: 0.08
  maintenance_cost_per_kw: 20
  min_observation_days: 90
model:
  building_feat_dim: 15
  hidden_dim: 128
  lv_feat_dim: 12
  max_hops: 3
  num_clusters: 10
  temporal_feat_dim: 8
  temporal_window: 24
  transformer_feat_dim: 8
output_dir: test_outputs
solar:
  max_capacity_per_building: 100.0
  min_roof_area: 20.0
training:
  T_0: 10
  T_mult: 2
  discovery_epochs: 10
  eta_min: 1.0e-06
  experiment_dir: test_experiments
  learning_rate: 0.001
  solar_epochs: 10
  weight_decay: 0.0001
