# config/config.yaml
# Main configuration file for the Energy GNN System

# Neo4j Database Connection
neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "aminasad"  # Change in production
  database: "neo4j"  # Default database
  
# Data Paths
paths:
  mimic_data: "mimic_data"
  processed_data: "processed_data"
  model_checkpoints: "checkpoints"
  logs: "logs"
  results: "results"
  metrics_db: "metrics.db"
  
# Graph Construction Parameters
graph:
  # Node types to extract
  node_types:
    - Building
    - MV_Transformer
    - LV_Network
    - Substation
    
  # Relationship types to extract
  edge_types:
    - CONNECTED_TO
    - ADJACENT_TO
    - SHARES_TRANSFORMER
    - IN_NETWORK
    - COMPLEMENTS  # Will be discovered by GNN
    
  # Adjacency matrix construction
  spatial:
    distance_threshold: 500  # meters
    distance_sigma: 100  # for exponential decay
    
  temporal:
    correlation_threshold: 0.3  # minimum correlation for edge
    correlation_window: 96  # 24 hours at 15-min intervals
    
# Model Architecture
model:
  type: "homo"  # Options: hetero, homo, multi_rel, adaptive
  # Model configuration parameters
  input_dim: 14  # Input feature dimension (matches Neo4j data)
  output_dim: 10  # Output dimension  
  hidden_dim: 128  # Hidden layer dimension
  num_layers: 3  # Number of GNN layers
  dropout: 0.2  # Dropout rate
  conv_type: "sage"  # Convolution type for homo model
  
  # Input dimensions
  input:
    building_features: 45  # Static + dynamic features
    transformer_features: 12
    edge_features: 8
    embedding_dim: 32  # KG embedding dimension
    
  # Hidden layers
  hidden:
    gnn_layers: 3
    hidden_dim: 128
    attention_heads: 8
    dropout: 0.2
    activation: "relu"
    
  # Temporal processing
  temporal:
    sequence_length: 96  # 24 hours at 15-min
    gru_hidden: 64
    gru_layers: 2
    
  # Physics constraints
  physics:
    enforce_kirchhoff: true
    voltage_tolerance: 0.05  # 5% deviation
    power_factor_min: 0.85
    
# Training Configuration
training:
  # Basic settings
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  epochs: 200
  early_stopping_patience: 20
  
  # Multi-task weights (initial)
  task_weights:
    clustering: 1.0
    solar: 0.8
    retrofit: 0.7
    thermal: 0.6
    electrification: 0.7
    battery: 0.8
    p2p_trading: 0.6
    congestion: 0.9
    
  # Optimization
  optimizer: "adam"
  scheduler: "cosine"
  gradient_clip: 1.0
  
  # Validation
  validation_split: 0.15
  test_split: 0.15
  cross_validation_folds: 5
  
# Inference Configuration
inference:
  confidence_threshold: 0.7
  max_recommendations: 10
  ensemble_models: 3
  uncertainty_estimation: true
  
# Logging and Monitoring
logging:
  level: "INFO"
  tensorboard: true
  wandb:
    enabled: false
    project: "energy-gnn"
    entity: "your-team"
  
  # Metrics to track
  metrics:
    - loss
    - accuracy
    - peak_reduction
    - self_sufficiency
    - modularity
    - intervention_roi
    
# Hardware Configuration
hardware:
  device: "cuda"  # cuda, cpu, or mps (Mac)
  num_workers: 4
  pin_memory: true
  mixed_precision: false