data:
  data_dir: data/processed
features:
  building_features:
  - area
  - height
  - age
  - energy_label
  - roof_area
  - orientation
  - occupancy
  edge_features:
  - distance
  - cable_capacity
  - resistance
  temporal_features:
  - hour
  - day_of_week
  - month
loss:
  w_cluster: 1.0
  w_flow: 1.0
  w_physics: 10.0
  w_placement: 1.0
model:
  dropout: 0.1
  edge_features: 3
  hidden_dim: 256
  max_clusters: 20
  node_features: 17
  num_layers: 3
neo4j:
  password: aminasad
  uri: neo4j://127.0.0.1:7687
  user: neo4j
training:
  batch_size: 32
  checkpoint_interval: 10
  grad_clip: 1.0
  learning_rate: 0.001
  scheduler_T0: 10
  weight_decay: 1.0e-05
